### ISSUE TITLE
Inkface should support non-layered and multi-layered SVG documents.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jay3sh/altcanvas#34]
```
What steps will reproduce the problem?
1. create svg without any grouping
2. run simple test as attached
3. exception raised

What is the expected output? What do you see instead?


What version of the product are you using? On what operating system?


Please provide any additional information below.

Traceback (most recent call last):
  File "test.py", line 42, in <module>
    app = Frame(theme)
  File "test.py", line 10, in __init__
    self.face = PygameFace(os.path.join(self.theme,'start.svg'))
  File
"/home/nibyrne01/Projects/inkface/build/lib/inkface/canvas/pygamecanvas.py", 
line
87, in __init__
    Face.__init__(self,svgname)
  File
"/home/nibyrne01/Projects/inkface/build/lib/inkface/canvas/canvas.py", line
21, in __init__
    self.svgelements = self.svg.get_elements()
  File
"/home/nibyrne01/Projects/inkface/build/lib/inkface/altsvg/__init__.py",
line 119, in get_elements
    for e in root_g.getchildren():
AttributeError: 'NoneType' object has no attribute 'getchildren'


```

Original issue reported on code.google.com by `nickjby...@gmail.com` on 26 Mar 2009 at 1:09

Attachments:
- [test.py](https://storage.googleapis.com/google-code-attachments/altcanvas/issue-34/comment-0/test.py)
- [start.svg](https://storage.googleapis.com/google-code-attachments/altcanvas/issue-34/comment-0/start.svg)

**Comment by GoogleCodeExporter** [comment]
```
That's quite an unique SVG file. Thanks for submitting it. Let me see how I can 
fix it.
```

Original comment by `jayeshsa...@gmail.com` on 26 Mar 2009 at 6:03
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
Thanks for quick response, it was just a standard output of
inkscape-0.46-6.fc10.1.i386 (from fedora repo). I didn't do anything special to
produce it, unless of course your comment was directed towards my unique 
graphical
design abilities :)
```

Original comment by `nickjby...@gmail.com` on 26 Mar 2009 at 12:08

**Comment by GoogleCodeExporter** [comment]
```
I was referring to the SVG syntax. It's interesting to see how different people
manage to get slightly varying SVG document structures using the same version of
Inkscape. I will read the spec regarding this particular tag and will fix the 
code
accordingly. Whether in spec or not, if something is generated by Inkscape, then
inkface library should not complain about it as well.
```

Original comment by `jayeshsa...@gmail.com` on 26 Mar 2009 at 3:10

**Comment by GoogleCodeExporter** [comment]
```
The basic problem is inkface currently parses the document assuming there is at 
least
one "layer" (a special 'g' group created by inkscape). This g group node is
considered root_g and all its children are processed. Therefore currently 
inkface
only works for exactly 1 layer. It will err out like reported in this bug when 
there
are zero layers (i.e. the elements are direct children of SVG node) and it will
ignore all upper layers when there are more than one layers.

This is not acceptable, but was a working solution so far. I am working on
reorganizing the code to fix this. I may wait and also take a look at generic 
SVG doc
created by Adobe Illustrator, so that I don't again end up with specific 
assumptions.
Meanwhile updating the summary to reflect the big picture. 
```

Original comment by `jayeshsa...@gmail.com` on 27 Mar 2009 at 6:18
- Changed title: **Inkface should support non-layered and multi-layered SVG documents.**

**Comment by GoogleCodeExporter** [comment]
```
Fixed in r1186. Now zero layer and multi layered docs are loaded.

Nick, I hope you don't mind that I have included your SVG file as part of test 
svgs
(tests/data/shape17.svg) (after changing colors of rectangles).
```

Original comment by `jayeshsa...@gmail.com` on 27 Mar 2009 at 2:32
- Changed state: **Fixed**
